--------NEED TO GO THROUGH AND DOUBLE CHECK EVERYTHING-----------------


--beacons DONE
local BeaconsBlacklist = {"base"}
local BeaconsSubOrder =
{
    ["speed"] = "[b]",
    ["productivity"] = "[c]",
    ["effectivity"] = "[d]",
    ["beacon"] = "[a]",
    ["ki"] = "[a]",
}
local BeaconsRecipeOrder =
{
    ["module"] = "[a]",
    ["compact"] = "[b]",
    ["wide"] = "[b]",
    ["recipe"] = "[c]",
}
--circuits
local CircuitBlacklist = { "aeroframe", "data", "recycle", "cybersyn" }
local CircuitSubOrder =
{
    ["combinator"] = "[e]",
    ["pole"] = "[a]",
    ["pylon"] = "[c]",
    ["substation"] = "[b]",
    ["buoy"] = "[d]",
    ["lamp"] = "[g]",
    ["switch"] = "[e]",
    ["signal"] = "[f]",
    ["speaker"] = "[e]",
}
local CircuitRecipeOrder =
{
    ["constant"] = "[a]",
    ["decider"] = "[a]",
    ["arithmetic"] = "[a]",
    ["wooden"] = "[c]",
    ["small"] = "[b]",
    ["medium"] = "[d]",
    ["big"] = "[e]",
    ["floating"] = "[e]",
    ["addon"] = "[a]",
    ["wire"] = "[a]",
    ["light"] = "[a]",
    ["mk2"] = "[b]",
    ["se"] = "[a]",
    ["programmable"] = "[a]",
    ["power"] = "[a]",
    ["receiver"] = "[a]",
}
--space
local SpaceBlacklist = { "science", "recycle", "ore", "data", "scrapping" }
local SpaceSubOrder =
{
    ["spaceship"] = "[c]",
    ["silo"] = "[b]",
    ["pad"] = "[a]",
    ["satellite"] = "[d]",
    ["capsul"] = "[e]",
    ["probe"] = "[d]",
}
local SpaceRecipeOrder =
{
    ["tank"] = "[c]",
    ["engine"] = "[d]",
    ["floor"] = "[b]",
    ["wall"] = "[b]",
    ["gate"] = "[b]",
    ["console"] = "[a]",
    ["clamp"] = "[e]",
    ["space"] = "[b]",
    ["rocket"] = "[g]",
    ["void"] = "[c]",
    ["star"] = "[d]",
    ["belt"] = "[e]",
    ["gps"] = "[f]",
}
--ammo
local AmmoBlacklist = { "reactor", "kr", "dart-rifle", "dart-turret", "fuel", "artillery-turret","heavy-rocket-launcher" }
local AmmoSubOrder =
{
    ["anti-material"] = "[a]",
    ["railgun"] = "[d]",
    ["artillery"] = "[c]",
    ["biter"] = "[f]",
    ["spitter"] = "[f]",
    ["rifle"] = "[a]",
    ["ammo"] = "[b]",
    ["grenade"] = "[g]",
    ["capsule"] = "[g]",
    ["virus"] = "[a]",
    ["rocket"] = "[e]",
    ["dart"] = "[a]",
    ["atomic"] = "[a]",
}
local AmmoRecipeOrder =
{
    ["magazine"] = "[a]",
    ["recipe"] = "[a]",
    ["cluster"] = "[a]",
    ["big"] = "[a]",
    ["small"] = "[a]",
    ["medium"] = "[a]",
    ["behemoth"] = "[a]",
    ["kr"] = "[a]",
    ["slowdown"] = "[a]",
    ["poison"] = "[a]",
    ["defender"] = "[a]",
    ["distractor"] = "[a]",
    ["destroyer"] = "[a]",
    ["shell"] = "[a]",
    ["turret"] = "[a]",
    ["antimatter"] = "[a]",
    ["heavy"] = "[a]",
    ["bomb"] = "[a]",
}
--tiles
local TilesBlacklist = {"se-matter-fusion-dirty","fu_fusion_card_2_recipe"}
local TilesSubOrder =
{
    ["text"] = "[e]",
    ["landfill"] = "[f]",
    ["concrete"] = "[a]",
    ["platform"] = "[c]",
    ["display"] = "[d]",
    ["reinforced"] = "[b]",
    ["waterfill"] = "[f]",
    ["recycle"] = "[z]",
    ["particle"] = "[z]",
    ["fusion"] = "[z]",
}
local TilesRecipeOrder =
{
    ["plate"] = "[a]",
    ["plating"] = "[a]",
    ["scaffold"] = "[a]",
    ["copper"] = "[a]",
    ["steel"] = "[a]",
    ["iron"] = "[a]",
    ["hazard"] = "[a]",
    ["refined"] = "[a]",
    ["balanced"] = "[a]",
    ["2"] = "[a]",
    ["silica"] = "[a]",
    ["sand"] = "[a]",
    ["ore"] = "[a]",
    ["graphite"] = "[a]",
    ["zircon"] = "[a]",
    ["coal"] = "[a]",
    ["imersite"] = "[a]",
    ["vitamelange"] = "[a]",
    ["vulcanite"] = "[a]",
    ["cryonite"] = "[a]",
    ["rare"] = "[a]",
    ["scrap"] = "[a]",
    ["dirty"] = "[a]",
    ["fold"] = "[a]",
    ["stone"] = "[a]",
    ["uranium"] = "[a]",
    ["beryllium"] = "[a]",
    ["holmium"] = "[a]",
    ["iridium"] = "[a]",
    ["naquium"] = "[a]",
    ["pole"] = "[a]",
    ["radar"] = "[a]",
    ["substation"] = "[a]",
    ["decontamination"] = "[a]",
}
--transport
local TransportBlacklist = { "turret", "shell", "laboratory", "battery", "belt", "lifesupport", "card", "scrapping",
    "rocket", "fiber", "fuel","fi_robo_port_recipe", "el_tank_recipe", "roboport" }
local TransportSubOrder =
{
    ["spidertron"] = "[f]",
    ["rail"] = "[a]",
    ["locomotive"] = "[b]",
    ["train"] = "[g]",
    ["cybersyn"] = "[d]",
    ["rail-chain-signal"] = "[d]",
    ["rail-signal"] = "[d]",
    ["chain-buoy"] = "[e]",
    ["buoy"] = "[e]",
    ["chain_buoy"] = "[e]",
    ["train-stop"] = "[d]",
    ["port"] = "[e]",
    ["wagon"] = "[c]",
    ["tanker"] = "[c]",
    ["car"] = "[f]",
    ["hcraft"] = "[g]",
    ["mcraft"] = "[g]",
    ["tank"] = "[g]",
    ["boat"] = "[e]",
    ["oil_tanker"] = "[e]",
    ["additional"] = "[g]",
    ["bridge_base"] = "[a]",
}
local TransportRecipeOrder =
{
    ["equipment"] = "[a]",
    ["dock"] = "[a]",
    ["interface"] = "[a]",
    ["space"] = "[a]",
    ["combinator"] = "[a]",
    ["nuclear"] = "[a]",
    ["station"] = "[a]",
    ["gr"] = "[c]",
    ["cargo"] = "[a]",
    ["fluid"] = "[a]",
    ["power"] = "[a]",
    ["wood"] = "[a]",
    ["artillery"] = "[z]",
    ["recipe"] = "[c]",
    ["engine"] = "[c]",
    ["advanced"] = "[c]",
}
--power
local PowerBlacklist = { "equipment", "oxygen", "star", "lead", "gr_charger_recipe", "fu_boiler_recipe", "robo",
    "el_charger_recipe", "bi-bio-reactor", "stelar", "tokamak","plasma" }
local PowerSubOrder =
{
    ["solar"] = "[c]",
    ["accumulator"] = "[c]",
    ["turbine"] = "[c]",
    ["boiler"] = "[c]",
    ["reactor"] = "[c]",
    ["generator"] = "[c]",
    ["charger"] = "[c]",
    ["heat"] = "[c]",
    ["steam-engine"] = "[c]",
    ["kr-energy-storage"] = "[c]",
    ["pressurizer"] = "[c]",
    ["intergalactic"] = "[c]",
}
local PowerRecipeOrder =
{
    ["wind"] = "[a]",
    ["steam"] = "[a]",
    ["burner"] = "[a]",
    ["panel"] = "[a]",
    ["pipe"] = "[a]",
    ["exchanger"] = "[a]",
    ["electric"] = "[a]",
    ["battery"] = "[a]",
    ["gas"] = "[a]",
    ["bio"] = "[a]",
    ["matter"] = "[a]",
    ["nuclear"] = "[a]",
    ["condenser"] = "[a]",
    ["fusion"] = "[a]",
    ["big"] = "[a]",
    ["recipe"] = "[a]",
    ["space"] = "[a]",
    ["transceiver"] = "[c]",
}
--combat
local CombatBlacklist = {"data"}
local CombatSubOrder =
{
    ["cliff"] = "[a]",
    ["turret"] = "f",
    ["wall"] = "f",
    ["gate"] = "f",
    ["shield"] = "f",
}
local CombatRecipeOrder =
{
    ["stone"] = "a",
    ["concrete"] = "b",
    ["steel"] = "c",
    ["imersium"] = "d",
    ["projector"] = "e",
    ["gun"] = "[a]",
    ["electric"] = "[a]",
    ["artillery"] = "[a]",
    ["rocket"] = "[a]",
    ["railgun"] = "[a]",
    ["laser"] = "[a]",
    ["flamethrower"] = "[a]",
    ["dart"] = "[a]",
    ["explosives"] = "[a]",
}
--production
local ProductionBlacklist = {"head","coal","sulfur","kerosene","fi_refinery_basic_recipe","fu_drill_recipe","crystal","equipment","cube","card"}
local ProductionSubOrder =
{
    ["assembling"] = "c",
    ["drill"] = "a",
    ["extractor"] = "b",
    ["pumpjack"] = "d",
    ["furnace"] = "b",
    ["crafter"] = "j",
    ["laboratory"] = "j",
    ["facility"] = "j",
    ["refinery"] = "i",
    ["plant"] = "e",
    ["burner"] = "f",
    ["computer"] = "j",
    ["telescope"] = "j",
    ["energy"] = "z",
    ["centrifuge"] = "j",
    ["radiator"] = "j",
    ["charging"] = "z",
    ["crusher"] = "g",
    ["greenhouse"] = "g",
    ["lab"] = "h",
}
local ProductionRecipeOrder =
{
    ["space"] = "[a]",
    ["mining"] = "[a]",
    ["quarry"] = "[a]",
    ["crust"] = "[x]",
    ["moho"] = "[y]",
    ["mantle"] = "[z]",
    ["offshore"] = "[a]",
    ["jack"] = "[a]",
    ["stone"] = "[a]",
    ["steel"] = "[b]",
    ["electric"] = "[c]",
    ["industrial"] = "[d]",
    ["advanced"] = "[e]",
    ["arc"] = "[f]",
    ["fluid"] = "[a]",
    ["growth"] = "[a]",
    ["lifesupport"] = "[a]",
    ["thermodynamics"] = "[a]",
    ["biochemical"] = "[a]",
    ["decontamination"] = "[a]",
    ["genetics"] = "[a]",
    ["radiation"] = "[a]",
    ["super"] = "[a]",
    ["quantum"] = "[a]",
    ["seafloor"] = "[a]",
    ["transmitter"] = "[a]",
    ["receiver"] = "[a]",
    ["chemical"] = "[a]",
    ["stabilizer"] = "[a]",
    ["battery"] = "[a]",
    ["bio"] = "[a]",
    ["biusart"] = "[a]",
    ["singularity"] = "[a]",
    ["recycling"] = "[a]",
    ["machine"] = "[a]",
    ["fi"] = "[c]",
    ["gr"] = "[d]",
    ["el"] = "[a]",
    ["fu"] = "[b]",
    ["kr"] = "[d]",
}
--logistics
local LogisticsBlacklist = {"equipment","companion","substrate"}
local LogisticsSubOrder =
{
    ["underground-belt"] = "[f]",
    ["floating-belt"] = "[j]",
    ["floating-inserter"] = "[j]",
    ["floating"] = "[j]",
    ["belt"] = "[e]",
    ["splitter"] = "[g]",
    ["loader"] = "[h]",
    ["inserter"] = "[i]",
    ["chest"] = "[a]",
    ["aai-strongbox"] = "[b]",
    ["aai-storehouse"] = "[c]",
    ["aai-warehouse"] = "[d]",
    ["storage"] = "[k]",
    ["minibuffer"] = "[k]",
    ["pump"] = "[m]",
    ["duct"] = "[m]",
    ["pipe"] = "[l]",
    ["robo"] = "[n]",
    ["valve"] = "[m]",
    ["aai-loader"] = "[a]",
}
local LogisticsRecipeOrder =
{
    ["steel"] = "[a]",
    ["iron"] = "[i]",
    ["wood"] = "[h]",
    ["passive"] = "[c]",
    ["active"] = "[f]",
    ["buffer"] = "[d]",
    ["requester"] = "[e]",
    ["fluid"] = "[a]",
    ["tank"] = "[a]",
    ["small"] = "[a]",
    ["junction"] = "[a]",
    ["curve"] = "[a]",
    ["cross"] = "[a]",
    ["return"] = "[a]",
    ["end-point"] = "[a]",
    ["space"] = "[z]",
    ["storage"] = "[b]",
    ["fast"] = "[c]",
    ["express"] = "[d]",
    ["advanced"] = "[e]",
    ["superior"] = "[z]",
    ["burner"] = "[a]",
    ["filter"] = "[d]",
    ["stack"] = "[e]",
    ["elbow"] = "[a]",
    ["straight"] = "[a]",
    ["check"] = "[a]",
    ["flow"] = "[a]",
    ["construction"] = "[g]",
    ["logistic"] = "[g]",
    ["large"] = "[a]",
    ["charger"] = "[a]",
    ["port"] = "[a]",
    ["long"] = "[b]",
    ["ground"] = "[a]",
}
--resources
local ResourceBlacklist = { "landfill", "matter", "text", "stream", "formatting", "cannon", "machine", "inserter",
    "alloy", "nitinol", "sludge","shotgun","fence","crusher","battery","solar","bi-cokery","probe","science" }
local ResourceSubOrder =
{
    ["tin"] = "[c]",
    ["coal"] = "[l]",
    ["iron"] = "[a]",
    ["copper"] = "[b]",
    ["uranium"] = "[m]",
    ["rare"] = "[n]",
    ["lithium"] = "[z]",
    ["bismuth"] = "[d]",
    ["gold"] = "[o]",
    ["lead"] = "[e]",
    ["silver"] = "[z]",
    ["tungsten"] = "[p]",
    ["titanium"] = "[q]",
    ["zircon"] = "[f]",
    ["titan"] = "[r]",
    ["salt"] = "[z]",
    ["graphite"] = "[g]",
    ["imersite"] = "[s]",
    ["nickel"] = "[h]",
    ["zinc"] = "[i]",
    ["alumin"] = "[j]",
    ["manganese"] = "[k]",
    ["crystal"] = "[z]",
    ["stone"] = "[l]",
    ["seed"] = "[z]",
    ["fuel"] = "[t]",
    ["resin"] = "[u]",
    ["ash"] = "[v]",
    ["coke"] = "[l]",
    ["glass"] = "[l]",
    ["wood"] = "[z]",
    ["logs"] = "[z]",
    ["sand"] = "[l]",
    ["plutonium"] = "[a]",
    ["ceramic"] = "[z]",
    ["neodym"] = "[z]",
    ["flourite"] = "[z]",
    ["space"] = "[z]",
    
}
local ResourceRecipeOrder =
{
    ["core"] = "[a]",
    ["ore"] = "[b]",
    ["flak"] = "[b]",
    ["raw"] = "[b]",
    ["enriched"] = "[c]",
    ["filtration"] = "[z]",
    ["plate"] = "[e]",
    ["metals"] = "[e]",
    ["recycle"] = "[y]",
    ["cast"] = "[e]",
    ["pure"] = "[c]",
    ["ingot"] = "[f]",
    ["molten"] = "[d]",
    ["burn"] = "[y]",
    ["vulcanite"] = "[y]",
    ["239"] = "[y]",
    ["1"] = "[y]",
    ["2"] = "[y]",
    ["vc"] = "[y]",
    ["zirconia"] = "[b]",
    ["alumina"] = "[b]",
    ["purify"] = "[b]",
    ["charge"] = "[a]",
    ["brick"] = "[y]",
    ["grow"] = "[a]",
    ["crushed"] = "[y]",
    ["bi"] = "[y]",
    ["energy"] = "[y]",
    ["resin"] = "[y]",
    ["recipe"] = "[y]",
    ["solid"] = "[y]",
    ["atoms"] = "[y]",
}
--manufactoring (intermediat-products)
local ManufactoringBlacklist = {}
local ManufactoringSubOrder = 
{
    ["upgrade"] = "[y]",
    ["board"] = "[y]",
    ["electronic"] = "[y]",
    ["fi"] = "[y]",
    ["fu"] = "[y]",
    ["gr"] = "[y]",
}
local ManufactoringRecipeOrder =
{
    ["recipe"] = "[y]",
    ["phenolic"] = "[y]",
    ["fibreglass"] = "[y]",
    ["circuit"] = "[y]",
    ["components"] = "[y]",
    ["intergrated"] = "[y]",
    ["processing"] = "[y]",
}
--fluids
local FluidBlacklist = { "biter", "purify", "equipment", "train","water-recipe","se-matter-fusion-dirty" }
local FluidSubOrder =
{
    ["sulfur"] = "[a]",
    ["kerosene"] = "[a]",
    ["gas"] = "[a]",
    ["methan"] = "[a]",
    ["nitric"] = "[a]",
    ["battery"] = "[a]",
    ["plastic"] = "[a]",
    ["biomass"] = "[a]",
    ["cellulose"] = "[a]",
    ["strong"] = "[a]",
    ["vinyl"] = "[a]",
    ["hydrogen"] = "[a]",
    ["epoxy"] = "[a]",
    ["formaldehyde"] = "[a]",
    ["liquefaction"] = "[a]",
    ["water"] = "[a]",
    ["ammonia"] = "[a]",
    ["coolant"] = "[a]",
    ["star"] = "[a]",
    ["rich"] = "[a]",
    ["dirty"] = "[a]",
    ["neutron"] = "[a]",
    ["cracking"] = "[a]",
    ["sludge"] = "[a]",
    ["gel"] = "[a]",
    ["organotins"] = "[a]",
    ["oil"] = "[a]",
    ["stream"] = "[a]",
    ["stelerator"] = "[a]",
    ["tokamak"] = "[a]",
    ["exchanger"] = "[a]",
    ["activator"] = "[a]",
    ["ferric"] = "[a]",
}
local FluidRecipeOrder =
{
    ["bi"] = "[a]",
    ["refinery"] = "[a]",
    ["reforming"] = "[b]",
    ["acid"] = "[c]",
    ["growing"] = "[a]",
    ["crack"] = "[a]",
    ["chloride"] = "[a]",
    ["coal"] = "[a]",
    ["coke"] = "[a]",
    ["formaldehyde"] = "[a]",
    ["electrolysis"] = "[a]",
    ["melting"] = "[a]",
    ["space"] = "[a]",
    ["decontamination"] = "[a]",
    ["seperation"] = "[a]",
    ["kr"] = "[a]",
    ["heavy"] = "[a]",
    ["lithium"] = "[a]",
    ["vent"] = "[a]",
    ["fluid"] = "[a]",
    ["recipe"] = "[a]",
    ["engine"] = "[a]",
    ["solution"] = "[a]",
    ["extract"] = "[a]",
    ["processing"] = "[a]",
    ["light"] = "[a]",
    ["chemical"] = "[a]",
    ["nutrient"] = "[a]",
    ["particle"] = "[a]",
    ["plasma"] = "[a]",
    ["ion"] = "[a]",
    ["proton"] = "[a]",
    ["antimatter"] = "[a]",
}
--science
local ScienceBlacklist = {"se-fusion-test-data","gravit","infrared","micro","electromagnetic","shielding","monopole","basic",
"blank","optimization","singularity","advanced"}
--first string to look for and what order to set the subgroup
local ScienceSubOrder =
{
    ["pack"] = "z",
    ["data"] = "z",
    ["tech"] = "z",
    ["card"] = "z",
}
--second string to look for and what order to set the item
local ScienceRecipeOrder =
{
    ["blue"] = "[a]",
    ["green"] = "[a]",
    ["white"] = "[a]",
    ["red"] = "[a]",
    ["black"] = "[a]",
    ["purple"] = "[a]",
    ["yellow"] = "[a]",
    ["grey"] = "[a]",
    ["stacked"] = "[a]",
    ["sign"] = "z",
    ["fusion"] = "z",
    ["laser"] = "z",
    ["magnet"] = "z",
    ["plasma"] = "z",
}

GroupBlacklist = {
    ["beacons"] = BeaconsBlacklist,
    ["circuit"] = CircuitBlacklist,
    ["space"] = SpaceBlacklist,
    ["ammo"] = AmmoBlacklist,
    ["tiles"] = TilesBlacklist,
    ["transport"] = TransportBlacklist,
    ["power"] = PowerBlacklist,
    ["combat"] = CombatBlacklist,
    ["production"] = ProductionBlacklist,
    ["logistics"] = LogisticsBlacklist,
    ["resources"] = ResourceBlacklist,
    ["intermediate-products"] = ManufactoringBlacklist,
    ["fluids"] = FluidBlacklist,
    ["science"] = ScienceBlacklist,
}
GroupSubOrder = {
    ["beacons"] = BeaconsSubOrder,
    ["circuit"] = CircuitSubOrder,
    ["space"] = SpaceSubOrder,
    ["ammo"] = AmmoSubOrder,
    ["tiles"] = TilesSubOrder,
    ["transport"] = TransportSubOrder,
    ["power"] = PowerSubOrder,
    ["combat"] = CombatSubOrder,
    ["production"] = ProductionSubOrder,
    ["logistics"] = LogisticsSubOrder,
    ["resources"] = ResourceSubOrder,
    ["intermediate-products"] = ManufactoringSubOrder,
    ["fluids"] = FluidSubOrder,
    ["science"] = ScienceSubOrder,
}
GroupRecipeOrder = {
    ["beacons"] = BeaconsRecipeOrder,
    ["circuit"] = CircuitRecipeOrder,
    ["space"] = SpaceRecipeOrder,
    ["ammo"] = AmmoRecipeOrder,
    ["tiles"] = TilesRecipeOrder,
    ["transport"] = TransportRecipeOrder,
    ["power"] = PowerRecipeOrder,
    ["combat"] = CombatRecipeOrder,
    ["production"] = ProductionRecipeOrder,
    ["logistics"] = LogisticsRecipeOrder,
    ["resources"] = ResourceRecipeOrder,
    ["intermediate-products"] = ManufactoringRecipeOrder,
    ["fluids"] = FluidRecipeOrder,
    ["science"] = ScienceRecipeOrder,
}
--this sorts the recipes into these groups in this order
GroupSortOrder = { "beacons", "space", "transport", "circuit", "ammo", "tiles", "power", "combat", "production",
    "logistics", "resources", "fluids", "science","intermediate-products" }

ReplaceSubgroup = {
    ["fuel-recycle"] = "uranium",
    ["gr-tanker"] = "wagon",
    ["gr-wagon"] = "wagon",
    ["gr-train"] = "locomotive",
    ["recipe-train"] = "locomotive",
    ["train-station"] = "rail-signal",
    ["cybersyn-combinator"] = "rail-signal",
    ["hcraft-recipe"] = "vehicle",
    ["mcraft-recipe"] = "vehicle",
    ["tank-advanced"] = "vehicle",
    ["cargo-ship"] = "watervehicle",
    ["additional-engine"] = "train",
    ["gps-satellite"] = "probe",
    ["atomic-bomb"] = "rocket",
    ["bio-boiler"] = "reactor",
    ["gas-boiler"] = "reactor",
    ["electric-boiler"] = "reactor",
    ["generator-fluid"] = "turbine",
    ["generator-recipe"] = "turbine",
    ["pressurizer-recipe"] = "turbine",
    ["intergalactic-transceiver"] = "accumulator",
    ["shield-projector"] = "wall",
    ["floating-long"] = "floating",
    ["floating-burner"] = "floating",
    ["floating-filter"] = "floating",
    ["floating-stack"] = "floating",
    ["floating-superior"] = "floating",
    ["ceramic-recipe"] = "stone",
    ["crafter-fi"] = "assembling",
    ["crafter-gr"] = "assembling",
    ["crust-extractor"] = "drill",
    ["mantle-extractor"] = "drill",
    ["moho-extractor"] = "drill",
    ["plant-chemical"] = "refinery",
}
--ADDD ORDER TO MEEE!!
ReplaceSubgroupDirectName =
{
    ["satellite"] = "probe",
    ["rail-signal"] = "rail-signal",
    ["rail-chain-signal"] = "rail-signal",
    ["chain_buoy"] = "port",
    ["buoy"] = "port",
    ["train-stop"] = "rail-signal",
    ["car"] = "vehicle",
    ["tank"] = "vehicle",
    ["boat"] = "watervehicle",
    ["bridge_base"] = "rail",
    ["oil_tanker"] = "watervehicle",
    ["steam-engine"] = "turbine",
    ["kr-energy-storage"] = "accumulator",
    ["boiler"] = "reactor",
    ["gate"] = "wall",
    ["aai-loader"] = "loader",
    ["floating-belt"] = "floating",
    ["floating-inserter"] = "floating",
}

--ADD ORDER TO ME!!!
SortDirectTable =
{
    ["vehicle-roboport"] = "train",
    ["fi_equipment_player_reactor_recipe"] = "equipment",
    ["fi_equipment_player_shield_recipe"] = "equipment",
    ["el_tank_recipe"] = "storage",
    ["se-supercharger"] = "robo",
    ["fi_castor_recipe"] = "burner",
    ["el_burner_recipe"] = "generator",
    ["el_burner_kerosene_recipe"] = "generator",
    ["burner-turbine"] = "generator",
    ["kr-wind-turbine"] = "generator",
    ["gr_black_hole_recipe"] = "generator",
    ["fu_miner_recipe"] = "drill",
    ["fi_miner_upgrade_recipe"] = "drill",
    ["fu_miner_upgrade_recipe"] = "drill",
    ["gr_miner_upgrade_recipe"] = "drill",
    ["se-casting-machine"] = "furnace",
    ["offshore-pump"] = "pumpjack",
    ["gas-extractor"] = "pumpjack",
    ["oil_rig"] = "pumpjack",
    ["se-core-miner"] = "drill",
    ["fuel-processor"] = "furnace",
    ["se-space-hypercooler"] = "radiator",
    ["bi-cokery"] = "furnace",
    ["bi-bio-reactor"] = "refinery",
    ["se-pulveriser"] = "crusher",
    ["se-nexus"] = "laboratory",
    ["se-space-plasma-generator"] = "facility",
    ["se-space-particle-collider"] = "laboratory",
    ["se-space-particle-accelerator"] = "laboratory",
    ["se-space-material-fabricator"] = "laboratory",
    ["kr-research-server"] = "computer",
    ["kr-matter-assembler"] = "plant",
    ["kr-atmospheric-condenser"] = "plant",
    ["kr-air-purifier"] = "burner",
    ["el_caster_recipe"] = "furnace",
    ["fu_ingot_recipe"] = "furnace",
    ["bi-bio-farm"] = "greenhouse",
    ["bi-arboretum"] = "greenhouse",
    ["bi-bio-garden"] = "greenhouse",
    ["kr-bio-lab"] = "greenhouse",
    ["fu_plasma_recipe"] = "248klead",
    ["fu_activator_recipe"] = "248klead",
    ["fu_fusor_recipe"] = "248klead",
    ["fu_laser_recipe"] = "248klead",
    ["fu_magnet_recipe"] = "248klead",
    ["fu_boiler_recipe"] = "248klead",
    ["fu_exchanger_item_recipe"] = "248klead",
    ["fu_tekamak_reactor_recipe"] = "248klead",
    ["fu_tokamak_reactor_recipe"] = "248klead",
    ["fu_stelar_reactor_recipe"] = "248klead",
    ["fu_star_engine_core_recipe"] = "248kstar",
    ["fu_star_engine_cooler_recipe"] = "248kstar",
    ["fu_star_engine_cooler_up_recipe"] = "248kstar",
    ["fu_star_engine_heater_left_recipe"] = "248kstar",
    ["fu_star_engine_heater_recipe"] = "248kstar",
    ["gr_charger_recipe"] = "248kextra",
    ["gr_white_hole_recipe"] = "248kextra",
    ["fi_compound_machine_recipe"] = "248kextra",
    ["fi_fiberer_recipe"] = "248kextra",
    ["el_purifier_recipe"] = "248kextra",
    ["el_grower_recipe"] = "248kextra",
    ["el_charger_recipe"] = "248kextra",
    ["el_ALK_recipe"] = "stone",
    ["fi_decay_waste_recipe"] = "uranium",
    ["fu_mining_recipe"] = "stone",
    ["kr-gas-power-station"] = "generator",
    ["se-arcosphere-collector"] = "probe",
    ["se-kr-experimental-matter-processing"] = "fusion",
    ["se-space-capsule-scorched-scrapping"] = "recycle",
    ["se-space-capsule-scrapping"] = "recycle",
    ["se-empty-barrel-reprocessing"] = "recycle",
    ["space-train-battery-pack-refurbish"] = "recycle",
    ["se-broken-data-scrapping"] = "recycle",
    ["se-cargo-pod-scrapping"] = "recycle",
    ["se-scrap-decontamination"] = "recycle",
    ["se-scrap-recycling"] = "recycle",
    ["fu_pure_ore_recipe"] = "lead",
    ["fi_ki_cpu_memory_circuit_recipe"] = "pack",
    ["fu_ki_cpu_memory_circuit_recipe"] = "pack",
    ["fu_space_probe_science_recipe"] = "pack",
    ["pistol-magazine-bismuth"] = "rifle",
    ["kr-tesla-coil"] = "switch",
    ["dirsty-water-filtration-3"] = "rare",
    ["fi_refinery_coal_recipe"] = "kerosene",
    ["fi_refinery_kerosene_coal_recipe"] = "kerosene",
    ["fi_refinery_basic_recipe"] = "kerosene",
    ["coal-filtration"] = "liquefaction",
    ["fu_metal_foam_recipe"] = "alumin",
    ["fu_treat_slag_recipe"] = "dirty",
    ["gr_wheel_recipe"] = "gear-components",
    ["gr_steel_recipe"] = "iron",
    ["advanced-circuit"] = "electronic",
    ["processing-unit"] = "electronic",
    ["advanced-processing-unit"] = "electronic",
    ["bob-rubber"] = "electronic",
    ["insulated-cable"] = "electronic",
    ["gr_circuit_recipe"] = "electronic",
    ["brass-from-atoms"] = "zinc",
    ["invar-from-atoms"] = "nickel",
    ["gr_materials_charge_recipe"] = "equipment",
    ["gr_materials_charge_remote_recipe"] = "equipment",
    ["gr_data_recipe"] = "data",
}
