local regroup = require("functions/regroup")

regroup.create_subgroup("tool", "combat", "raw-01")
regroup.create_subgroup("defensive-structure", "combat", "raw-02")
regroup.create_subgroup("radars-and-rockets", "combat", "raw-03")
regroup.create_subgroup("gun", "combat", "raw-04")
regroup.create_subgroup("ammo", "combat", "raw-05")
regroup.create_subgroup("bi-ammo", "combat", "raw-06")
regroup.create_subgroup("firearm-magazine", "combat", "raw-07")
regroup.create_subgroup("shotgun-shell", "combat", "raw-08")
regroup.create_subgroup("large-caliber-rifle-magazine", "combat", "raw-09")
regroup.create_subgroup("rifle-magazine", "combat", "raw-10")
regroup.create_subgroup("flamethrower", "combat", "raw-11")
regroup.create_subgroup("se-gun", "combat", "raw-12")
regroup.create_subgroup("launcher-capsule", "combat", "raw-13")
regroup.create_subgroup("cannon-shell", "combat", "raw-14")
regroup.create_subgroup("rocket", "combat", "raw-15")
regroup.create_subgroup("railgun-turret", "combat", "raw-16")
regroup.create_subgroup("rocket-turret", "combat", "raw-17")
regroup.create_subgroup("laser", "combat", "raw-18")
regroup.create_subgroup("artillery", "combat", "raw-19")
regroup.create_subgroup("surface-defense", "combat", "raw-20")
regroup.create_subgroup("capsule", "combat", "raw-21")
regroup.create_subgroup("armor", "combat", "raw-22")
regroup.create_subgroup("reactor-equipment", "combat", "raw-23")
regroup.create_subgroup("solar-panel-equipment", "combat", "raw-24")
regroup.create_subgroup("battery-equipment", "combat", "raw-25")
regroup.create_subgroup("defense-equipment", "combat", "raw-26")
regroup.create_subgroup("equipment", "combat", "raw-27")
regroup.create_subgroup("character-equipment", "combat", "raw-28")
regroup.create_subgroup("vehicle-motor", "combat", "raw-29")

-- tool
regroup.set_subgroup_to_prototype("repair-pack", "tool", "01")
regroup.set_subgroup_to_prototype("copper-repair-pack", "tool", "02")
regroup.set_subgroup_to_prototype("copper-repair-recipe", "tool", "02")
regroup.set_subgroup_to_prototype("steel-repair-pack", "tool", "03")
regroup.set_subgroup_to_prototype("steel-repair-recipe", "tool", "03")
regroup.set_subgroup_to_prototype("field-repair-pack", "tool", "04")
regroup.set_subgroup_to_prototype("field-repair-recipe", "tool", "04")
regroup.set_subgroup_to_prototype("multitool-repair-pack", "tool", "05")
regroup.set_subgroup_to_prototype("multitool-repair-recipe", "tool", "05")

-- defensive-structure
regroup.set_subgroup_to_prototype("bi-wooden-fence", "defensive-structure", "01")
regroup.set_subgroup_to_prototype("stone-wall", "defensive-structure", "02")
regroup.set_subgroup_to_prototype("concrete-wall", "defensive-structure", "03")
regroup.set_subgroup_to_prototype("steel-wall", "defensive-structure", "04")
regroup.set_subgroup_to_prototype("gate", "defensive-structure", "05")
regroup.set_subgroup_to_prototype("shield-projector", "defensive-structure", "06")

-- bi-ammo
regroup.set_subgroup_to_prototype("bi-dart-turret", "bi-ammo", "[bio-ammo]-a-[0]")
regroup.set_subgroup_to_prototype("bi-dart-rifle", "bi-ammo", "[bio-ammo]-a-[1]")

-- firearm-magazine
regroup.set_subgroup_to_prototype("pistol", "firearm-magazine", "01")
regroup.set_subgroup_to_prototype("firearm-magazine", "firearm-magazine", "02")
regroup.set_subgroup_to_prototype("pistol-magazine-bismuth", "firearm-magazine", "03")
regroup.set_subgroup_to_prototype("high-capacity-firearm-magazine", "firearm-magazine", "04")
regroup.set_subgroup_to_prototype("piercing-rounds-magazine", "firearm-magazine", "05")
regroup.set_subgroup_to_prototype("high-capacity-piercing-rounds-magazine", "firearm-magazine", "06")

-- shotgun-shell
regroup.set_subgroup_to_prototype("shotgun-item-rampant-arsenal", "shotgun-shell", "01")
regroup.set_subgroup_to_prototype("shotgun", "shotgun-shell", "02")
regroup.set_subgroup_to_prototype("combat-shotgun", "shotgun-shell", "03")
regroup.set_subgroup_to_prototype("shotgun-shell", "shotgun-shell", "04")
regroup.set_subgroup_to_prototype("high-capacity-shotgun-shell", "shotgun-shell", "05")
regroup.set_subgroup_to_prototype("piercing-shotgun-shell", "shotgun-shell", "06")
regroup.set_subgroup_to_prototype("high-capacity-piercing-shotgun-shell", "shotgun-shell", "07")
regroup.set_subgroup_to_prototype("uranium-shotgun-shell", "shotgun-shell", "08")
regroup.set_subgroup_to_prototype("uranium-shotgun-recipe", "shotgun-shell", "08")
regroup.set_subgroup_to_prototype("high-capacity-uranium-shotgun-shell", "shotgun-shell", "09")
regroup.set_subgroup_to_prototype("high-capacity-uranium-shotgun-recipe", "shotgun-shell", "09")
regroup.set_subgroup_to_prototype("bio-shotgun-ammo-rampant-arsenal", "shotgun-shell", "10")
regroup.set_subgroup_to_prototype("he-shotgun-ammo-rampant-arsenal", "shotgun-shell", "11")
regroup.set_subgroup_to_prototype("incendiary-shotgun-ammo-rampant-arsenal", "shotgun-shell", "12")
regroup.set_subgroup_to_prototype("uranium-shotgun-ammo-rampant-arsenal", "shotgun-shell", "13")

-- large-caliber-rifle-magazine
regroup.set_subgroup_to_prototype("anti-material-rifle", "large-caliber-rifle-magazine", "01")
regroup.set_subgroup_to_prototype("anti-material-rifle-magazine", "large-caliber-rifle-magazine", "02")
regroup.set_subgroup_to_prototype("armor-piercing-anti-material-rifle-magazine", "large-caliber-rifle-magazine", "03")
regroup.set_subgroup_to_prototype("explosive-rounds-anti-material-rifle-magazine", "large-caliber-rifle-magazine", "04")
regroup.set_subgroup_to_prototype("uranium-anti-material-rifle-magazine", "large-caliber-rifle-magazine", "05")
regroup.set_subgroup_to_prototype("imersite-anti-material-rifle-magazine", "large-caliber-rifle-magazine", "06")

-- rifle-magazine
regroup.set_subgroup_to_prototype("rifle-item-rampant-arsenal", "rifle-magazine", "01")
regroup.set_subgroup_to_prototype("gun-turret", "rifle-magazine", "02")
regroup.set_subgroup_to_prototype("gun-item-rampant-arsenal", "rifle-magazine", "03")
regroup.set_subgroup_to_prototype("submachine-gun", "rifle-magazine", "04")
regroup.set_subgroup_to_prototype("minigun-gun-rampant-arsenal", "rifle-magazine", "05")
regroup.set_subgroup_to_prototype("rifle-magazine", "rifle-magazine", "06")
regroup.set_subgroup_to_prototype("rifle-magazine-bismuth", "rifle-magazine", "07")
regroup.set_subgroup_to_prototype("armor-piercing-rifle-magazine", "rifle-magazine", "08")
regroup.set_subgroup_to_prototype("explosive-rounds-rifle-magazine", "rifle-magazine", "09")
regroup.set_subgroup_to_prototype("uranium-rifle-magazine", "rifle-magazine", "10")
regroup.set_subgroup_to_prototype("high-capacity-uranium-rounds-magazine", "rifle-magazine", "11")
regroup.set_subgroup_to_prototype("imersite-rifle-magazine", "rifle-magazine", "12")
regroup.set_subgroup_to_prototype("water-magazine", "rifle-magazine", "13")
regroup.set_subgroup_to_prototype("water-recipe", "rifle-magazine", "13")
regroup.set_subgroup_to_prototype("sp-rounds-magazine", "rifle-magazine", "14")
regroup.set_subgroup_to_prototype("sp-ammo-recipe", "rifle-magazine", "14")
regroup.set_subgroup_to_prototype("high-capacity-sp-rounds-magazine", "rifle-magazine", "15")
regroup.set_subgroup_to_prototype("high-capacity-sp-ammo-recipe", "rifle-magazine", "15")
regroup.set_subgroup_to_prototype("tungsten-rounds-magazine", "rifle-magazine", "16")
regroup.set_subgroup_to_prototype("tungsten-ammo-recipe", "rifle-magazine", "16")
regroup.set_subgroup_to_prototype("high-capacity-tungsten-rounds-magazine", "rifle-magazine", "17")
regroup.set_subgroup_to_prototype("high-capacity-tungsten-ammo-recipe", "rifle-magazine", "17")
regroup.set_subgroup_to_prototype("fmj-rounds-magazine", "rifle-magazine", "18")
regroup.set_subgroup_to_prototype("fmj-ammo-recipe", "rifle-magazine", "18")
regroup.set_subgroup_to_prototype("high-capacity-fmj-rounds-magazine", "rifle-magazine", "19")
regroup.set_subgroup_to_prototype("high-capacity-fmj-ammo-recipe", "rifle-magazine", "19")
regroup.set_subgroup_to_prototype("cryonite-rounds-magazine", "rifle-magazine", "20")
regroup.set_subgroup_to_prototype("cryonite-ammo-recipe", "rifle-magazine", "20")
regroup.set_subgroup_to_prototype("high-capacity-cryonite-rounds-magazine", "rifle-magazine", "21")
regroup.set_subgroup_to_prototype("high-capacity-cryonite-ammo-recipe", "rifle-magazine", "21")
regroup.set_subgroup_to_prototype("cryonite-rounds-magazine", "rifle-magazine", "22")
regroup.set_subgroup_to_prototype("cryonite-ammo-recipe", "rifle-magazine", "22")
regroup.set_subgroup_to_prototype("high-capacity-cryonite-rounds-magazine", "rifle-magazine", "23")
regroup.set_subgroup_to_prototype("high-capacity-cryonite-ammo-recipe", "rifle-magazine", "23")
regroup.set_subgroup_to_prototype("vulcanite-rounds-magazine", "rifle-magazine", "24")
regroup.set_subgroup_to_prototype("vulcanite-ammo-recipe", "rifle-magazine", "24")
regroup.set_subgroup_to_prototype("high-capacity-vulcanite-rounds-magazine", "rifle-magazine", "25")
regroup.set_subgroup_to_prototype("high-capacity-vulcanite-ammo-recipe", "rifle-magazine", "25")
regroup.set_subgroup_to_prototype("beryllium-rounds-magazine", "rifle-magazine", "26")
regroup.set_subgroup_to_prototype("beryllium-ammo-recipe", "rifle-magazine", "26")
regroup.set_subgroup_to_prototype("high-capacity-beryllium-rounds-magazine", "rifle-magazine", "27")
regroup.set_subgroup_to_prototype("high-capacity-beryllium-ammo-recipe", "rifle-magazine", "27")
regroup.set_subgroup_to_prototype("naquium-rounds-magazine", "rifle-magazine", "28")
regroup.set_subgroup_to_prototype("naquium-ammo-recipe", "rifle-magazine", "28")
regroup.set_subgroup_to_prototype("high-capacity-naquium-rounds-magazine", "rifle-magazine", "29")
regroup.set_subgroup_to_prototype("high-capacity-naquium-ammo-recipe", "rifle-magazine", "29")
regroup.set_subgroup_to_prototype("iridium-rounds-magazine", "rifle-magazine", "30")
regroup.set_subgroup_to_prototype("iridium-ammo-recipe", "rifle-magazine", "30")
regroup.set_subgroup_to_prototype("high-capacity-iridium-rounds-magazine", "rifle-magazine", "31")
regroup.set_subgroup_to_prototype("high-capacity-iridium-ammo-recipe", "rifle-magazine", "31")
regroup.set_subgroup_to_prototype("fire-rounds-magazine", "rifle-magazine", "32")
regroup.set_subgroup_to_prototype("fire-ammo-recipe", "rifle-magazine", "32")
regroup.set_subgroup_to_prototype("high-capacity-fire-rounds-magazine", "rifle-magazine", "33")
regroup.set_subgroup_to_prototype("high-capacity-fire-ammo-recipe", "rifle-magazine", "33")
regroup.set_subgroup_to_prototype("acid-rounds-magazine", "rifle-magazine", "34")
regroup.set_subgroup_to_prototype("acid-ammo-recipe", "rifle-magazine", "34")
regroup.set_subgroup_to_prototype("high-capacity-acid-rounds-magazine", "rifle-magazine", "35")
regroup.set_subgroup_to_prototype("high-capacity-acid-ammo-recipe", "rifle-magazine", "35")
regroup.set_subgroup_to_prototype("he-rounds-magazine", "rifle-magazine", "36")
regroup.set_subgroup_to_prototype("he-ammo-recipe", "rifle-magazine", "36")
regroup.set_subgroup_to_prototype("high-capacity-he-rounds-magazine", "rifle-magazine", "37")
regroup.set_subgroup_to_prototype("high-capacity-he-ammo-recipe", "rifle-magazine", "37")
regroup.set_subgroup_to_prototype("bio-magazine-ammo-rampant-arsenal", "rifle-magazine", "38")
regroup.set_subgroup_to_prototype("he-magazine-ammo-rampant-arsenal", "rifle-magazine", "39")
regroup.set_subgroup_to_prototype("incendiary-magazine-ammo-rampant-arsenal", "rifle-magazine", "40")

-- flamethrower
regroup.set_subgroup_to_prototype("flamethrower-turret", "flamethrower", "01")
regroup.set_subgroup_to_prototype("acid-cannon-rampant-arsenal", "flamethrower", "02")
regroup.set_subgroup_to_prototype("acid-cannon-rampant-arsenal", "flamethrower", "03")
regroup.set_subgroup_to_prototype("suppression-cannon-item-rampant-arsenal", "flamethrower", "04")
regroup.set_subgroup_to_prototype("flamethrower", "flamethrower", "05")
regroup.set_subgroup_to_prototype("flamethrower-ammo", "flamethrower", "06")
regroup.set_subgroup_to_prototype("napalm-ammo-rampant-arsenal", "flamethrower", "07")

-- launcher-capsule
regroup.set_subgroup_to_prototype("capsule-item-rampant-arsenal", "launcher-capsule", "01")
regroup.set_subgroup_to_prototype("lite-artillery-turret-rampant-arsenal", "launcher-capsule", "02")
regroup.set_subgroup_to_prototype("artillery-targeting-remote-rampant-arsenal", "launcher-capsule", "03")
regroup.set_subgroup_to_prototype("mortar-gun-rampant-arsenal", "launcher-capsule", "04")

-- se-gun
regroup.set_subgroup_to_prototype("se-railgun", "se-gun", "01")
regroup.set_subgroup_to_prototype("se-railgun-ammo", "se-gun", "02")
regroup.set_subgroup_to_prototype("impulse-rifle", "se-gun", "03")
regroup.set_subgroup_to_prototype("impulse-rifle-ammo", "se-gun", "04")
regroup.set_subgroup_to_prototype("se-cryogun", "se-gun", "05")
regroup.set_subgroup_to_prototype("se-cryogun-ammo", "se-gun", "06")
regroup.set_subgroup_to_prototype("se-biogun", "se-gun", "07")
regroup.set_subgroup_to_prototype("se-bloater-ammo", "se-gun", "08")
regroup.set_subgroup_to_prototype("se-pheromone-ammo", "se-gun", "09")
regroup.set_subgroup_to_prototype("se-tesla-gun", "se-gun", "10")
regroup.set_subgroup_to_prototype("se-tesla-ammo", "se-gun", "11")
regroup.set_subgroup_to_prototype("grappling-gun", "se-gun", "12")
regroup.set_subgroup_to_prototype("grappling-gun-ammo", "se-gun", "13")

-- cannon-shell
regroup.set_subgroup_to_prototype("cannon-item-rampant-arsenal", "cannon-shell", "01")
regroup.set_subgroup_to_prototype("rapid-cannon-item-rampant-arsenal", "cannon-shell", "02")
regroup.set_subgroup_to_prototype("cannon-shell", "cannon-shell", "03")
regroup.set_subgroup_to_prototype("explosive-cannon-shell", "cannon-shell", "04")
regroup.set_subgroup_to_prototype("uranium-cannon-shell", "cannon-shell", "05")
regroup.set_subgroup_to_prototype("explosive-uranium-cannon-shell", "cannon-shell", "06")
regroup.set_subgroup_to_prototype("bio-cannon-shell-ammo-rampant-arsenal", "cannon-shell", "07")
regroup.set_subgroup_to_prototype("he-cannon-shell-ammo-rampant-arsenal", "cannon-shell", "08")
regroup.set_subgroup_to_prototype("incendiary-cannon-shell-ammo-rampant-arsenal", "cannon-shell", "09")

-- rocket
regroup.set_subgroup_to_prototype("rocket-item-rampant-arsenal", "rocket", "01")
regroup.set_subgroup_to_prototype("rapid-rocket-item-rampant-arsenal", "rocket", "02")
regroup.set_subgroup_to_prototype("rocket-launcher", "rocket", "03")
regroup.set_subgroup_to_prototype("rocket-launcher-gun-rampant-arsenal", "rocket", "04")
regroup.set_subgroup_to_prototype("heavy-rocket-launcher", "rocket", "05")
regroup.set_subgroup_to_prototype("rocket", "rocket", "06")
regroup.set_subgroup_to_prototype("explosive-rocket", "rocket", "07")
regroup.set_subgroup_to_prototype("se-plague-bomb", "rocket", "08")
regroup.set_subgroup_to_prototype("heavy-rocket", "rocket", "09")
regroup.set_subgroup_to_prototype("atomic-bomb", "rocket", "10")
regroup.set_subgroup_to_prototype("fi_atomic_bomb_recipe", "rocket", "102")
regroup.set_subgroup_to_prototype("antimatter-rocket", "rocket", "11")
regroup.set_subgroup_to_prototype("bio-rocket-ammo-rampant-arsenal", "rocket", "12")
regroup.set_subgroup_to_prototype("he-rocket-ammo-rampant-arsenal", "rocket", "13")
regroup.set_subgroup_to_prototype("incendiary-rocket-ammo-rampant-arsenal", "rocket", "14")

-- laser
regroup.set_subgroup_to_prototype("laser-turret", "laser", "01")
regroup.set_subgroup_to_prototype("lightning-item-rampant-arsenal", "laser", "02")
regroup.set_subgroup_to_prototype("advanced-beam-item-rampant-arsenal", "laser", "03")
regroup.set_subgroup_to_prototype("advanced-laser-item-rampant-arsenal", "laser", "04")
regroup.set_subgroup_to_prototype("kr-laser-artillery-turret", "laser", "05")

-- artillery
regroup.set_subgroup_to_prototype("artillery-turret", "artillery", "01")
regroup.set_subgroup_to_prototype("artillery-shell", "artillery", "02")
regroup.set_subgroup_to_prototype("nuclear-artillery-shell", "artillery", "03")
regroup.set_subgroup_to_prototype("antimatter-artillery-shell", "artillery", "04")
regroup.set_subgroup_to_prototype("bio-artillery-ammo-rampant-arsenal", "artillery", "05")
regroup.set_subgroup_to_prototype("he-artillery-ammo-rampant-arsenal", "artillery", "06")
regroup.set_subgroup_to_prototype("incendiary-artillery-ammo-rampant-arsenal", "artillery", "07")
regroup.set_subgroup_to_prototype("nuclear-artillery-ammo-rampant-arsenal", "artillery", "08")

-- reactor-equipment
regroup.set_subgroup_to_prototype("small-portable-generator", "reactor-equipment", "01")
regroup.set_subgroup_to_prototype("portable-generator", "reactor-equipment", "02")
regroup.set_subgroup_to_prototype("se-rtg-equipment", "reactor-equipment", "03")
regroup.set_subgroup_to_prototype("se-rtg-equipment-2", "reactor-equipment", "04")
regroup.set_subgroup_to_prototype("mk3-generator-rampant-arsenal", "reactor-equipment", "05")
regroup.set_subgroup_to_prototype("nuclear-generator-rampant-arsenal", "reactor-equipment", "06")
regroup.set_subgroup_to_prototype("fi_equipment_player_reactor_item", "reactor-equipment", "07")
regroup.set_subgroup_to_prototype("fi_equipment_player_reactor_recipe", "reactor-equipment", "07")
regroup.set_subgroup_to_prototype("fi_train_equipment_generator_item", "reactor-equipment", "08")
regroup.set_subgroup_to_prototype("fi_train_equipment_generator_recipe", "reactor-equipment", "08")
regroup.set_subgroup_to_prototype("nuclear-reactor-equipment", "reactor-equipment", "09")
regroup.set_subgroup_to_prototype("fusion-reactor-equipment", "reactor-equipment", "10")
regroup.set_subgroup_to_prototype("antimatter-reactor-equipment", "reactor-equipment", "11")

-- solar-panel-equipment
regroup.set_subgroup_to_prototype("solar-panel-equipment", "solar-panel-equipment", "01")
regroup.set_subgroup_to_prototype("big-solar-panel-equipment", "solar-panel-equipment", "02")
regroup.set_subgroup_to_prototype("imersite-solar-panel-equipment", "solar-panel-equipment", "03")
regroup.set_subgroup_to_prototype("big-imersite-solar-panel-equipment", "solar-panel-equipment", "04")

-- battery-equipment
regroup.set_subgroup_to_prototype("battery-equipment", "battery-equipment", "01")
regroup.set_subgroup_to_prototype("big-battery-equipment", "battery-equipment", "02")
regroup.set_subgroup_to_prototype("battery-mk2-equipment", "battery-equipment", "03")
regroup.set_subgroup_to_prototype("mk3-battery-rampant-arsenal", "battery-equipment", "04")
regroup.set_subgroup_to_prototype("big-battery-mk2-equipment", "battery-equipment", "05")
regroup.set_subgroup_to_prototype("battery-mk3-equipment", "battery-equipment", "06")
regroup.set_subgroup_to_prototype("big-battery-mk3-equipment", "battery-equipment", "07")

-- defense-equipment
regroup.set_subgroup_to_prototype("personal-submachine-laser-defense-mk1-equipment", "defense-equipment", "01")
regroup.set_subgroup_to_prototype("personal-submachine-laser-defense-mk2-equipment", "defense-equipment", "02")
regroup.set_subgroup_to_prototype("personal-submachine-laser-defense-mk3-equipment", "defense-equipment", "03")
regroup.set_subgroup_to_prototype("personal-submachine-laser-defense-mk4-equipment", "defense-equipment", "04")
regroup.set_subgroup_to_prototype("personal-laser-defense-equipment", "defense-equipment", "05")
regroup.set_subgroup_to_prototype("personal-laser-defense-mk2-equipment", "defense-equipment", "06")
regroup.set_subgroup_to_prototype("personal-laser-defense-mk3-equipment", "defense-equipment", "07")
regroup.set_subgroup_to_prototype("personal-laser-defense-mk4-equipment", "defense-equipment", "08")
regroup.set_subgroup_to_prototype("shotgun-passive-defense-rampant-arsenal", "defense-equipment", "09")
regroup.set_subgroup_to_prototype("cannon-passive-defense-rampant-arsenal", "defense-equipment", "10")
regroup.set_subgroup_to_prototype("lightning-passive-defense-rampant-arsenal", "defense-equipment", "11")
regroup.set_subgroup_to_prototype("bullets-passive-defense-rampant-arsenal", "defense-equipment", "12")
regroup.set_subgroup_to_prototype("slow-passive-defense-rampant-arsenal", "defense-equipment", "13")

-- character-equipment
regroup.set_subgroup_to_prototype("fi_equipment_player_shield_item", "character-equipment", "s[energy-shield]-a6")
regroup.set_subgroup_to_prototype("fi_equipment_player_shield_recipe", "character-equipment", "s[energy-shield]-a6")
regroup.set_subgroup_to_prototype("mk3-shield-rampant-arsenal", "character-equipment", "s[energy-shield]-s21")

-- vehicle-motor
regroup.set_subgroup_to_prototype("el_train_equipment_generator_item", "vehicle-motor", "f-1")
regroup.set_subgroup_to_prototype("el_train_equipment_generator_recipe", "vehicle-motor", "f-1")
regroup.set_subgroup_to_prototype("el_train_equipment_accelerator_item", "vehicle-motor", "f-2")
regroup.set_subgroup_to_prototype("el_train_equipment_accelerator_recipe", "vehicle-motor", "f-2")
