local regroup = require("functions/regroup")

regroup.create_subgroup("container-1", "logistics", "raw-01")
regroup.create_subgroup("container-2", "logistics", "raw-02")
regroup.create_subgroup("container-4", "logistics", "raw-03")
regroup.create_subgroup("container-6", "logistics", "raw-04")
regroup.create_subgroup("storage", "logistics", "raw-05")
regroup.create_subgroup("belt", "logistics", "raw-06")
regroup.create_subgroup("transport-belt", "logistics", "raw-07")
regroup.create_subgroup("underground-belt", "logistics", "raw-08")
regroup.create_subgroup("splitter", "logistics", "raw-09")
regroup.create_subgroup("inserter", "logistics", "raw-10")
regroup.create_subgroup("energy-pipe-distribution-middle", "logistics", "raw-11")
regroup.create_subgroup("energy-pipe-distribution-big", "logistics", "raw-12")
regroup.create_subgroup("energy-pipe-distribution-substation", "logistics", "raw-13")
regroup.create_subgroup("logistic-drones", "logistics", "raw-14")
regroup.create_subgroup("logistic-network", "logistics", "raw-15")
regroup.create_subgroup("circuit-network", "logistics", "raw-16")
regroup.create_subgroup("rocket-logistics", "logistics", "raw-17")
regroup.create_subgroup("spaceship-structure", "logistics", "raw-18")

-- energy-pipe-distribution-middle
regroup.set_subgroup_to_prototype("small-electric-pole", "energy-pipe-distribution-middle", "01")
regroup.set_subgroup_to_prototype("lighted-small-electric-pole", "energy-pipe-distribution-middle", "02")
regroup.set_subgroup_to_prototype("small-iron-electric-pole", "energy-pipe-distribution-middle", "03")
regroup.set_subgroup_to_prototype("lighted-small-iron-electric-pole", "energy-pipe-distribution-middle", "04")
regroup.set_subgroup_to_prototype("medium-electric-pole", "energy-pipe-distribution-middle", "05")
regroup.set_subgroup_to_prototype("lighted-medium-electric-pole", "energy-pipe-distribution-middle", "06")
regroup.set_subgroup_to_prototype("se-addon-power-pole", "energy-pipe-distribution-middle", "07")
regroup.set_subgroup_to_prototype("lighted-se-addon-power-pole", "energy-pipe-distribution-middle", "08")

-- energy-pipe-distribution-big
regroup.set_subgroup_to_prototype("bi-wooden-pole-big", "energy-pipe-distribution-big", "01")
regroup.set_subgroup_to_prototype("lighted-bi-wooden-pole-big", "energy-pipe-distribution-big", "02")
regroup.set_subgroup_to_prototype("bi-wooden-pole-huge", "energy-pipe-distribution-big", "03")
regroup.set_subgroup_to_prototype("lighted-bi-wooden-pole-huge", "energy-pipe-distribution-big", "04")
regroup.set_subgroup_to_prototype("big-electric-pole", "energy-pipe-distribution-big", "05")
regroup.set_subgroup_to_prototype("lighted-big-electric-pole", "energy-pipe-distribution-big", "06")
regroup.set_subgroup_to_prototype("bp_extreme_power_pole", "energy-pipe-distribution-big", "07")
regroup.set_subgroup_to_prototype("lighted-bp_extreme_power_pole", "energy-pipe-distribution-big", "08")
regroup.set_subgroup_to_prototype("se-pylon", "energy-pipe-distribution-big", "09")
regroup.set_subgroup_to_prototype("lighted-se-pylon", "energy-pipe-distribution-big", "10")
regroup.set_subgroup_to_prototype("se-pylon-construction", "energy-pipe-distribution-big", "11")
regroup.set_subgroup_to_prototype("lighted-se-pylon-construction", "energy-pipe-distribution-big", "12")

-- energy-pipe-distribution-substation
regroup.set_subgroup_to_prototype("substation", "energy-pipe-distribution-substation", "01")
regroup.set_subgroup_to_prototype("lighted-substation", "energy-pipe-distribution-substation", "02")
regroup.set_subgroup_to_prototype("kr-substation-mk2", "energy-pipe-distribution-substation", "03")
regroup.set_subgroup_to_prototype("lighted-kr-substation-mk2", "energy-pipe-distribution-substation", "04")
regroup.set_subgroup_to_prototype("bi-large-substation", "energy-pipe-distribution-substation", "05")
regroup.set_subgroup_to_prototype("lighted-bi-large-substation", "energy-pipe-distribution-substation", "06")
regroup.set_subgroup_to_prototype("se-pylon-substation", "energy-pipe-distribution-substation", "07")
regroup.set_subgroup_to_prototype("lighted-se-pylon-substation", "energy-pipe-distribution-substation", "08")
regroup.set_subgroup_to_prototype("se-pylon-construction-radar", "energy-pipe-distribution-substation", "09")
regroup.set_subgroup_to_prototype("lighted-se-pylon-construction-radar", "energy-pipe-distribution-substation", "10")
regroup.set_subgroup_to_prototype("kr-tesla-coil", "energy-pipe-distribution-substation", "11")
regroup.set_subgroup_to_prototype("kr-planetary-teleporter", "energy-pipe-distribution-substation", "12")

-- logistic-drones
regroup.set_subgroup_to_prototype("logistic-robot", "logistic-drones", "01")
regroup.set_subgroup_to_prototype("construction-robot", "logistic-drones", "02")
regroup.set_subgroup_to_prototype("fu_robo_logistic_item", "logistic-drones", "03")
regroup.set_subgroup_to_prototype("fu_robo_logistic_recipe", "logistic-drones", "03")
regroup.set_subgroup_to_prototype("fu_robo_construction_item", "logistic-drones", "04")
regroup.set_subgroup_to_prototype("fu_robo_construction_recipe", "logistic-drones", "04")

-- logistic-network
regroup.set_subgroup_to_prototype("roboport", "logistic-network", "01")
regroup.set_subgroup_to_prototype("fi_robo_charger_item", "logistic-network", "02")
regroup.set_subgroup_to_prototype("fi_robo_charger_recipe", "logistic-network", "02")
regroup.set_subgroup_to_prototype("fi_robo_port_item", "logistic-network", "03")
regroup.set_subgroup_to_prototype("fi_robo_port_recipe", "logistic-network", "03")
regroup.set_subgroup_to_prototype("kr-small-roboport", "logistic-network", "04")
regroup.set_subgroup_to_prototype("kr-large-roboport", "logistic-network", "05")
regroup.set_subgroup_to_prototype("se-supercharger", "logistic-network", "06")
