local regroup = require("functions/regroup")

regroup.create_subgroup("energy", "production", "raw-01")
regroup.create_subgroup("energy-nuclear", "production", "raw-02")
regroup.create_subgroup("nuclear", "production", "raw-03")
regroup.create_subgroup("solar-panels", "production", "raw-04")
regroup.create_subgroup("accumulators", "production", "raw-05")
regroup.create_subgroup("extraction-machine", "production", "raw-06")
regroup.create_subgroup("offshore-pumps", "production", "raw-07")
regroup.create_subgroup("water-pumpjacks", "production", "raw-08")
regroup.create_subgroup("assembling", "production", "raw-09")
regroup.create_subgroup("smelting-machine", "production", "raw-10")
regroup.create_subgroup("chemistry", "production", "raw-11")
regroup.create_subgroup("bio-chemistry", "production", "raw-12")
regroup.create_subgroup("production-machine", "production", "raw-13")
regroup.create_subgroup("mechanical", "production", "raw-14")
regroup.create_subgroup("plasma", "production", "raw-15")
regroup.create_subgroup("cooling", "production", "raw-16")
regroup.create_subgroup("computation", "production", "raw-17")
regroup.create_subgroup("telescope", "production", "raw-18")
regroup.create_subgroup("beaming", "production", "raw-19")
regroup.create_subgroup("lab", "production", "raw-20")

-- energy-nuclear
regroup.set_subgroup_to_prototype("nuclear-reactor", "energy-nuclear", "01")
regroup.set_subgroup_to_prototype("fi_solid_reactor_item", "energy-nuclear", "02")
regroup.set_subgroup_to_prototype("fi_solid_reactor_recipe", "energy-nuclear", "02")
regroup.set_subgroup_to_prototype("se-antimatter-reactor", "energy-nuclear", "03")
regroup.set_subgroup_to_prototype("se-antimatter-reactor", "energy-nuclear", "03")
regroup.set_subgroup_to_prototype("kr-fusion-reactor", "energy-nuclear", "04")
regroup.set_subgroup_to_prototype("kr-antimatter-reactor", "energy-nuclear", "05")
regroup.set_subgroup_to_prototype("fu_tokamak_reactor_item", "energy-nuclear", "06")
regroup.set_subgroup_to_prototype("fu_tokamak_reactor_recipe", "energy-nuclear", "06")
regroup.set_subgroup_to_prototype("fu_stelar_reactor_item", "energy-nuclear", "07")
regroup.set_subgroup_to_prototype("fu_stelar_reactor_recipe", "energy-nuclear", "07")

-- nuclear
regroup.set_subgroup_to_prototype("centrifuge", "nuclear", "01")
regroup.set_subgroup_to_prototype("se-space-radiation-laboratory", "nuclear", "02")
regroup.set_subgroup_to_prototype("heat-exchanger", "nuclear", "03")
regroup.set_subgroup_to_prototype("heat-pipe", "nuclear", "04")
regroup.set_subgroup_to_prototype("se-naquium-heat-pipe", "nuclear", "05")
regroup.set_subgroup_to_prototype("se-naquium-heat-pipe-long--+--", "nuclear", "06")
regroup.set_subgroup_to_prototype("se-naquium-heat-pipe-long--+-----+--", "nuclear", "07")

-- solar-panels
regroup.set_subgroup_to_prototype("solar-panel", "solar-panels", "01")
regroup.set_subgroup_to_prototype("el_solar_item", "solar-panels", "02")
regroup.set_subgroup_to_prototype("el_solar_recipe", "solar-panels", "02")
regroup.set_subgroup_to_prototype("kr-advanced-solar-panel", "solar-panels", "03")
regroup.set_subgroup_to_prototype("se-space-solar-panel", "solar-panels", "04")
regroup.set_subgroup_to_prototype("se-space-solar-panel-2", "solar-panels", "05")
regroup.set_subgroup_to_prototype("se-space-solar-panel-3", "solar-panels", "06")
regroup.set_subgroup_to_prototype("bi-bio-solar-farm", "solar-panels", "07")
regroup.set_subgroup_to_prototype("bi-solar-mat", "solar-panels", "08")

-- accumulators
regroup.set_subgroup_to_prototype("accumulator", "accumulators", "01")
regroup.set_subgroup_to_prototype("se-space-accumulator", "accumulators", "02")
regroup.set_subgroup_to_prototype("se-space-accumulator-2", "accumulators", "03")
regroup.set_subgroup_to_prototype("bi-bio-accumulator", "accumulators", "04")
regroup.set_subgroup_to_prototype("kr-energy-storage", "accumulators", "05")

-- offshore-pumps
regroup.set_subgroup_to_prototype("offshore-pump-0", "offshore-pumps", "01")
regroup.set_subgroup_to_prototype("offshore-pump-1", "offshore-pumps", "02")
regroup.set_subgroup_to_prototype("offshore-pump-2", "offshore-pumps", "03")
regroup.set_subgroup_to_prototype("offshore-pump-3", "offshore-pumps", "04")
regroup.set_subgroup_to_prototype("offshore-pump-4", "offshore-pumps", "05")

-- water-pumpjacks
regroup.set_subgroup_to_prototype("water-pumpjack-1", "water-pumpjacks", "01")
regroup.set_subgroup_to_prototype("water-pumpjack-2", "water-pumpjacks", "02")
regroup.set_subgroup_to_prototype("water-pumpjack-3", "water-pumpjacks", "03")
regroup.set_subgroup_to_prototype("water-pumpjack-4", "water-pumpjacks", "04")
regroup.set_subgroup_to_prototype("water-pumpjack-5", "water-pumpjacks", "05")

-- assembling
regroup.set_subgroup_to_prototype("burner-assembling-machine", "assembling", "01")
regroup.set_subgroup_to_prototype("assembling-machine-1", "assembling", "02")
regroup.set_subgroup_to_prototype("assembling-machine-2", "assembling", "03")
regroup.set_subgroup_to_prototype("assembling-machine-3", "assembling", "04")
regroup.set_subgroup_to_prototype("kr-advanced-assembling-machine", "assembling", "05")
regroup.set_subgroup_to_prototype("se-space-assembling-machine", "assembling", "06")
regroup.set_subgroup_to_prototype("se-space-manufactory", "assembling", "07")
regroup.set_subgroup_to_prototype("fi_crafter_item", "assembling", "08")
regroup.set_subgroup_to_prototype("fi_crafter_recipe", "assembling", "08")
regroup.set_subgroup_to_prototype("gr_crafter_item", "assembling", "09")
regroup.set_subgroup_to_prototype("gr_crafter_recipe", "assembling", "09")

-- smelting-machine
regroup.set_subgroup_to_prototype("stone-furnace", "smelting-machine", "01")
regroup.set_subgroup_to_prototype("steel-furnace", "smelting-machine", "02")
regroup.set_subgroup_to_prototype("electric-furnace", "smelting-machine", "03")
regroup.set_subgroup_to_prototype("foundry", "smelting-machine", "04")
regroup.set_subgroup_to_prototype("electric-foundry", "smelting-machine", "05")
regroup.set_subgroup_to_prototype("industrial-furnace", "smelting-machine", "06")
regroup.set_subgroup_to_prototype("kr-advanced-furnace", "smelting-machine", "07")
regroup.set_subgroup_to_prototype("se-casting-machine", "smelting-machine", "08")
regroup.set_subgroup_to_prototype("se-space-thermodynamics-laboratory", "smelting-machine", "09")

-- chemistry
regroup.set_subgroup_to_prototype("basic-chemical-plant", "chemistry", "01")
regroup.set_subgroup_to_prototype("chemical-plant", "chemistry", "02")
regroup.set_subgroup_to_prototype("oil-refinery", "chemistry", "03")
regroup.set_subgroup_to_prototype("fi_refinery_item", "chemistry", "04")
regroup.set_subgroup_to_prototype("fi_refinery_recipe", "chemistry", "04")
regroup.set_subgroup_to_prototype("kr-advanced-chemical-plant", "chemistry", "05")
regroup.set_subgroup_to_prototype("fuel-processor", "chemistry", "06")
regroup.set_subgroup_to_prototype("se-fuel-refinery", "chemistry", "07")
regroup.set_subgroup_to_prototype("se-fuel-refinery", "chemistry", "08")
regroup.set_subgroup_to_prototype("kr-fuel-refinery", "chemistry", "09")
regroup.set_subgroup_to_prototype("kr-electrolysis-plant", "chemistry", "10")
regroup.set_subgroup_to_prototype("kr-atmospheric-condenser", "chemistry", "11")
regroup.set_subgroup_to_prototype("kr-fluid-burner", "chemistry", "12")

-- bio-chemistry
regroup.set_subgroup_to_prototype("se-lifesupport-facility", "bio-chemistry", "01")
regroup.set_subgroup_to_prototype("se-space-biochemical-laboratory", "bio-chemistry", "02")
regroup.set_subgroup_to_prototype("se-space-decontamination-facility", "bio-chemistry", "03")
regroup.set_subgroup_to_prototype("se-space-genetics-laboratory", "bio-chemistry", "04")
regroup.set_subgroup_to_prototype("se-space-growth-facility", "bio-chemistry", "05")
regroup.set_subgroup_to_prototype("kr-bio-lab", "bio-chemistry", "06")
